language: python
python:
    - "2.7"
env:
    - SUPERVISOR_PYTHON_VERSION=2.7
install:
    - pip install -e .
    - pip install -e .[test]
    - pip install supervisor
script:
    - python -m unittest discover
sudo: false

